# Generated by Django 4.2.6 on 2023-12-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lat', models.CharField(max_length=255)),
                ('lng', models.CharField(max_length=255)),
                ('is_accepted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ClientOrder',
                'verbose_name_plural': 'ClientOrders',
            },
        ),
        migrations.CreateModel(
            name='DriverOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fromm', models.CharField(max_length=255)),
                ('to', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'DriverOrder',
                'verbose_name_plural': 'DriverOrders',
            },
        ),
    ]
