# Generated by Django 4.2.6 on 2023-12-21 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driverorders',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='driver_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_driver_order', to='orders.driverorders'),
        ),
        migrations.AlterUniqueTogether(
            name='clientorder',
            unique_together={('client', 'driver_order')},
        ),
    ]
