# Generated by Django 4.2.6 on 2023-10-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.IntegerField()),
                ('expire_date', models.DateTimeField()),
                ('phone_number', models.IntegerField()),
                ('is_verified', models.BooleanField()),
            ],
            options={
                'verbose_name': 'SMS',
                'verbose_name_plural': 'SMS',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('driver', 'Driver')], default='client', max_length=50),
        ),
    ]
