# Generated by Django 4.2.6 on 2023-11-19 03:11

import apps.users.validators
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_sms_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='code',
            field=models.IntegerField(validators=[apps.users.validators.activation_code_validator]),
        ),
        migrations.AlterField(
            model_name='sms',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 3, 17, 34, 663542, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sms',
            name='phone_number',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 9 digits long!', regex='^\\d{9}$')]),
        ),
    ]
