# Generated by Django 4.2.6 on 2023-11-25 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_sms_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 12, 39, 5, 853676, tzinfo=datetime.timezone.utc)),
        ),
    ]
