# Generated by Django 4.2.6 on 2023-11-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_sms_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
