# Generated by Django 4.2.6 on 2023-11-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_remove_driverorders_driver_delete_clientorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
